### ISSUE TITLE
NameError: name 'Path' is not defined

### ISSUE THREAD

**Issue by cvpe** [cclauss/Ten-lines-or-less#49]
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/94C45A26-1F47-4486-9539-896F8F44AA91/Pythonista3/Documents/a5.py", line 42, in <module>
    pythonista_version(),
  File "/private/var/mobile/Containers/Shared/AppGroup/94C45A26-1F47-4486-9539-896F8F44AA91/Pythonista3/Documents/a5.py", line 27, in pythonista_version
    info_plist = (Path(sys.executable).parent / "Info.plist").read_bytes()
NameError: name 'Path' is not defined

**Comment by cvpe** [comment]
Then, I wanted to use old way with

plist = plistlib.readPlist(os.path.abspath(os.path.join(sys.executable, '..', 'Info.plist')))

 But new error

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/94C45A26-1F47-4486-9539-896F8F44AA91/Pythonista3/Documents/a5.py", line 31, in <module>
    print(pythonista_version())
  File "/private/var/mobile/Containers/Shared/AppGroup/94C45A26-1F47-4486-9539-896F8F44AA91/Pythonista3/Documents/a5.py", line 24, in pythonista_version
    plist = plistlib.readPlist(os.path.abspath(os.path.join(sys.executable, '..', 'Info.plist')))
AttributeError: module 'plistlib' has no attribute 'readPlist'
